class PreparingOpeningFileToCreation

	def self.getingImportatedOpeningName(params)
		openingName = params.require(:path).to_s.split('/')
		openingName[openingName.length-1]
	end


	def self.getingImportatedOpeningMoveSequence(params)
		content = File.read(params.require(:path))
		if content.first(19) == "Generated by WZebra"
			getingMoveFromwzebraFile(content)
		else
			getingMoveFromPlayokFile(content)
		end
	end


	def self.getingMoveFromwzebraFile(fileString)
		fileString = fileString.split("History:")[1]
		move_sequence = ''
		moveCounter = 1
		while fileString.index(moveCounter.to_s+": ") != nil do
			moveIndex = fileString.index(moveCounter.to_s+": ") + (moveCounter > 9 ? 1 : 0) + 3
			move_sequence += fileString[moveIndex]+ fileString[moveIndex+1] + ' '
			moveCounter += 1
		end
		move_sequence
	end


	def self.getingMoveFromPlayokFile(fileString)
		content.split("]\r\n\r\n")[1]
	end

end
